apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glpi.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
        - name: glpi
          image: {{ .Values.glpi.image }}
          env:
            - name: GLPI_DB_HOST
              value: {{ include "glpi.fullname" . }}-db
            - name: GLPI_DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: GLPI_DB_USER
              value: {{ .Values.mariadb.auth.user | quote }}
            - name: GLPI_DB_PASSWORD
              value: {{ .Values.mariadb.auth.password | quote }}
            - name: GLPI_AUTO_INSTALL
              value: "false"
            # Belangrijk: Vertel GLPI waar de nieuwe mappen staan
            - name: GLPI_CONFIG_DIR
              value: "/etc/glpi"
            - name: GLPI_VAR_DIR
              value: "/var/lib/glpi"
            - name: GLPI_LOG_DIR
              value: "/var/log/glpi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: glpi-data
              mountPath: /var/lib/glpi # De map waar GLPI data opslaat
            - name: glpi-config
              mountPath: /etc/glpi
      volumes:
        - name: glpi-data
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-glpi-data-pvc
        - name: glpi-config
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-glpi-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "glpi.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: glpi
